#!/bin/bash
WALLET=$1
PASSWORD=$2
WORKER=$3
POOL=$4
PORT=$5
POOLFULL=$4":"$5
CPULIMIT=$6
WALLETFULL=$1$3

CONFIG="\"cpu_threads_conf\" :\n"
CONFIG+="[\n"
CONFIG+="  { \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 0 },\n"
CONFIG+="  { \"low_power_mode\" : false, \"no_prefetch\" : true, \"affine_to_cpu\" : 1 },\n"
CONFIG+="],\n"
CONFIG+="\"use_slow_memory\" : \"warn\",\n"
CONFIG+="\"nicehash_nonce\" : false,\n"
CONFIG+="\"aes_override\" : null,\n"
CONFIG+="\"use_tls\" : false,\n"
CONFIG+="\"tls_secure_algo\" : true,\n"
CONFIG+="\"tls_fingerprint\" : \"\",\n"
CONFIG+="\"pool_address\" : \"$POOLFULL\",\n"
CONFIG+="\"wallet_address\" : \"$WALLETFULL\",\n"
CONFIG+="\"pool_password\" : \"$PASSWORD\",\n"
CONFIG+="\"call_timeout\" : 10,\n"
CONFIG+="\"retry_time\" : 10,\n"
CONFIG+="\"giveup_limit\" : 0,\n"
CONFIG+="\"verbose_level\" : 3,\n"
CONFIG+="\"h_print_time\" : 60,\n"
CONFIG+="\"daemon_mode\" : false,\n"
CONFIG+="\"output_file\" : \"\",\n"
CONFIG+="\"httpd_port\" : 0,\n"
CONFIG+="\"prefer_ipv4\" : true,"


INTRO="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="-------------THIS SCRIPT DOWNLOAD, COMPILE, INSTALL AND MAKE SETTING OF XMR-STACK-CPU--------------\n"
INTRO+="-----------------------------AND INSTALL CPULIMIT FOR LIMIT CPU USAGE------------------------------\n"
INTRO+="---------------------------FOR A SIMPLE VPS RUNNING UBUNTU 16.04 SERVER----------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="-------------------------------------------DONATE XMR----------------------------------------------\n"
INTRO+="--48zHnevytL2Rbhf38Ma5msRtDeXvJ8d8pHCAw3NMdNd9iEGhnnnSZC1cfxdtVx32xN6BMDdfgDZHaaianRA831PyLPcy5tk--\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="-------------------------------------------by NoWheel----------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="USAGE:\n"
INTRO+=":~# ./install_mining_server {WALLET} {PASSWORD} {+NAMEOFWORKER} {POOL} {PERCENTAGEOFCPULIMIT}"
INTRO+="---------------------------------------------------------------------------------------------------\n"
INTRO+="---------------------------------------------------------------------------------------------------\n"

#!/bin/bash
if [[ $EUID -ne 0 ]]; then
    printf "%b" "$INTRO"
    echo "This script must be run as root."
    echo "Don't use \"sudo\", use \"sudo -i\" for entering in root shell"
    echo ""
    echo ""
    echo ""
    exit 1
fi

if [ $# -eq 0 ]; then
    printf "%b" "$INTRO"
    echo "WHERE IS YOUR WALLET?"
    echo ""
    echo ""
    echo ""
    exit 1
fi
if [ $# -eq 1 ]; then
    printf "%b" "$INTRO"
    echo "WHERE IS YOUR PASSWORD?"
    echo ""
    echo ""
    echo ""
    exit 1
fi
if [ $# -eq 2 ]; then
    printf "%b" "$INTRO"
    echo "WHERE IS YOUR NAME-OF-WORKER?"
    echo "if you don't want to set name of worker write: \"\""
    echo ""
    echo ""
    echo ""
    exit 1
fi
if [ $# -eq 3 ]; then
    printf "%b" "$INTRO"
    echo "WHERE IS YOUR POOL?"
    echo ""
    echo ""
    echo ""
    exit 1
fi
if [ $# -eq 4 ]; then
    printf "%b" "$INTRO"
    echo "WHERE IS YOUR PERCENTAGE-OF-CPU-LIMIT?"
    echo ""
    echo ""
    echo ""
    exit 1
fi


echo "---UPDATING SYSTEM---"
apt-get update
apt-get --assume-yes upgrade

echo "---INSTALL DEPENDENCING---"
sudo apt-get --assume-yes install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev screen git

echo "---DOWNLOAD,COMPILE, INSTALL AND CONFIGURE XMR-STAK-CPU"
git clone https://github.com/fireice-uk/xmr-stak-cpu.git
cd xmr-stak-cpu

echo "---compiling xmr-stak-cpu---"
cmake .

echo "---installing xmr-stak-cpu---"
make install
chmod +x bin/xmr-stak-cpu

echo "---make backup of original xmr-stak cpu config file---"
mv bin/config.txt bin/config.txt.old

echo "---setting your config---"
touch bin/config.txt
printf "%b\n" "$CONFIG" >> bin/config.txt
chown root bin/config.txt
cd ..

echo "---INSTALL CPULIMIT---"
apt-get --assume-yes install cpulimit

echo "--MAKE EXECUTABLE CUSTOM FILE---"
echo "cd xmr-stak-cpu/bin/ && ./xmr-stak-cpu" >> miner
echo "cpulimit --exe xmr-stak-cpu --limit $CPULIMIT" >> cpulimit-miner
chmod +x miner
chmod +x cpulimit-miner

echo "---SET EXECUTABLE RUNNING AT REBOOT---"
(crontab -l 2>/dev/null; echo "@reboot /root/cpulimit_miner")| crontab -
(crontab -l 2>/dev/null; echo "@reboot screen -d -m /root/miner")| crontab -

echo "---DELETE OLD FILES---"
cd xmr-stak-cpu
rm -rf !(bin)
cd ..
